# Generated by Django 2.2.4 on 2019-09-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='browseinfo',
            old_name='ip_id',
            new_name='ip',
        ),
    ]
