# Generated by Django 2.2.4 on 2019-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190907_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='K_USER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('logintime', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
